<?php


namespace App\HttpController\Admin;


use EasySwoole\Http\AbstractInterface\Controller;

class Base extends Controller
{


    protected function onRequest(?string $action): ?bool
    {

        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }


    // 设置更新粉丝
//    function set_totals()
//    {
//        //只要有接口调用 我就更新
//
//    }


}